spring.application.name=notificator
spring.datasource.url=jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5434}/${PG_DATABASE:notif}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.pbkdf2.secret=${PBKDF2_SECRET:notificator}
spring.pbkdf2.salt-length=${PBKDF2_SALT:100}
spring.pbkdf2.iterations=${PBKDF2_ITERATIONS:100}