CREATE TABLE IF NOT EXISTS reminder(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCE account(id),
    title VARCHAR(255) NOT NULL,
    description VARCHAR(4096),
    notify_time TIMESTAMP,
);